---
title: "Jeopardy Through the Years"
author: "Matt, Rachel, Shayna, Sherry"
output:
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE, echo = FALSE}

library(flexdashboard)
library(tidyverse)

```

Column{data-width=300}
-----------------------------------------------------------------------

### Background Information



Research Question: 

For all seasons of Jeopardy, from Season 1 through Season 35, 
what are the most common calendar years referenced in an answer? 

Results:
The top year was 1996. 
The decade of the '90s was the most commonly referenced overall. 

24% of all Jeopardy answers contained a year, with 1% of those being 1996. 

Spikes on the plots are seen at years ending in 0. This trend may be in part to 
the fact that the four digit years referenced are often in reference to a decade
(i.e. "The 1990's) or a century (i.e the 1900's)
```{r}
knitr::opts_chunk$set(echo = FALSE)

# read in data
clues <- read_tsv("./data/master_season1-35.tsv")

answers <- clues %>% 
  select(category, answer, question)

#filter years out of answers, create new column, arrange descending
years_data <- answers %>% 
  mutate(years = str_extract(answer, "[0-9]{4}")) %>%
  filter(str_count(years)==4)%>% 
  arrange(desc(years)) %>% 
  slice(413:84470) %>% 
  group_by(years) 

 years_data1 <- years_data %>% 
   summarize(count = n()) %>% 
   arrange(desc(count)) %>% 
   ungroup()

 # change years column to numeric 
years2 <- transform(years_data1, years = as.numeric(years))

# create table showing top 10 most frequent dates
top_10 <- years_data1 %>% 
  slice(1:10) %>% 
  mutate(count = prettyNum(count,big.mark = ","))

library(knitr)
top_10_table <- 
  kable(top_10, 
      align = c("r","r"),
      caption = "Top 10 most mentioned years")
top_10_table
```

Column{data-width=700}
-----------------------------------------------------------------------


### Frequency of years referenced

```{r}
line_plot <- ggplot(years2, aes(x = years, y = count)) +
  geom_line(color = "Blue") +
  xlab("Years") +
  ylab("Frequency")+
  ggtitle("Four digit years found in Jeopardy clues, Season 1-35") 

line_plot

library(plotly)
ggplotly(line_plot) %>% 
  rangeslider (start = 1000, end = 2020)


```


### Historical Context

```{r, fig.width = 10, fig.height = 5}
library(ggthemes)
reference_plot <- 
  ggplot() +
  geom_point(data = years2, aes(x = years, y = count))+
  coord_cartesian(xlim = c(1800,2019))+
  geom_vline(xintercept=1996,colour="blue")+
  geom_text(aes(x=1996,label="1996",y=1087,vjust=0,hjust=0),
            colour="black",
            text=element_text(size=11))+
  geom_text(aes(x=1995,label=
              "US Olympics",y=200),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1861,colour="blue")+
  geom_text(aes(x=1860, label=
              "American Civil War",y=350),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1914,colour="blue")+
  geom_text(aes(x=1913,label="WWI",y=500),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1939,colour="blue")+
  geom_text(aes(x=1938,label="WWII",y=500),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1955,colour="blue")+
  geom_text(aes(x=1954,label="Vietnam",y=100),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=2008,colour="blue")+
  geom_text(aes(x=2007,label="911 Attacks",y=200),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1963,colour="blue")+
  geom_text(aes(x=1962,label=
              "JFK Assassination",y=100),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1986,colour="blue")+
  geom_text(aes(x=1985,label=
              "Challenger Disaster",y=175),angle=90,vjust=0,hjust=0)+
   geom_vline(xintercept=1964,colour="red")+
  xlab("Years")+
  ylab("Frequency")+
  ggtitle("Four digit years (1800-2019) found in Jeopardy clues, Season 1-35",
          subtitle =  "red line = 1984 debut of Jeopardy")+
  theme_few()

reference_plot
```

