---
title: "R Final Project FlexDashBoard"
author: "Matt, Rachel, Shayna, Sherry"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE, messages = FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
library(tidyverse)
library(plotly)
clues <- read_tsv("./data/master_season1-35.tsv")
answers <- clues %>% 
  select(category, answer, question)
years_data <- answers %>% 
  mutate(years = str_extract(answer, "[0-9]{4}")) %>%
  filter(str_count(years)==4) %>% 
  slice(413:84470) %>% 
  group_by(years) %>% 
  mutate(count = n()) %>% 
  arrange(desc(count)) %>% 
  ungroup()
#years_data
ggplot(data = years_data)+
  stat_count(mapping = aes(x = years), color = "dark green")
years2 <- transform(years_data, years = as.numeric(years))
sapply(years2, mode)
years2
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

#

```

