---
title: "FlexDashBoard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
<<<<<<< HEAD:FlexDashBoard Matt Rachel Shayna Sherry.Rmd
library(tidyverse)
=======
knitr::opts_chunk$set(echo = TRUE)
=======
knitr::opts_chunk$set(echo = FALSE)
>>>>>>> d781491cef7db9ff9712c8b05cfc5bec08291a42:FlexDashBoard.Rmd
library(tidyverse)

clues <- read_tsv("./data/master_season1-35.tsv")

answers <- clues %>% 
  select(category, answer, question)

#filter years out of answers, create new column, arrange descending
years_data <- answers %>% 
  mutate(years = str_extract(answer, "[0-9]{4}")) %>%
  filter(str_count(years)==4)%>% 
  arrange(desc(years)) %>% 
  slice(413:84470) %>% 
  group_by(years) 

 years_data1 <- years_data %>% 
   summarize(count = n()) %>% 
   arrange(desc(count)) %>% 
   ungroup()
 
years2 <- transform(years_data1, years = as.numeric(years))

years2
nrow(years2)


```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

clues <- read_tsv("./data/master_season1-35.tsv")
=======
library(ggthemes)
reference_plot <- 
  ggplot() +
  geom_point(data = years2, aes(x = years, y = count))+
  coord_cartesian(xlim = c(1800,2019))+
  geom_vline(xintercept=1996,colour="blue")+
  geom_text(aes(x=1996,label="1996",y=1087,vjust=0,hjust=0),
            colour="black",
            text=element_text(size=11))+
  geom_text(aes(x=1995,label=
              "US Olympics",y=200),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1861,colour="blue")+
  geom_text(aes(x=1860, label=
              "American Civil War",y=350),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1914,colour="blue")+
  geom_text(aes(x=1913,label="WWI",y=500),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1939,colour="blue")+
  geom_text(aes(x=1938,label="WWII",y=500),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1955,colour="blue")+
  geom_text(aes(x=1954,label="Vietnam",y=100),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=2008,colour="blue")+
  geom_text(aes(x=2007,label="911 Attacks",y=200),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1963,colour="blue")+
  geom_text(aes(x=1962,label=
              "JFK Assassination",y=100),angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1986,colour="blue")+
  geom_text(aes(x=1985,label=
              "Challenger Disaster",y=175),angle=90,vjust=0,hjust=0)+
   geom_vline(xintercept=1964,colour="red")+
   geom_vline(xintercept=2000,colour="red")+
  xlab("Years")+
  ylab("Number of times year given in clue")+
  ggtitle("Four digit years found in Jeopardy clues,Season 1-35",
          subtitle = "Truncated from 1800-2019")+
  theme_few()

reference_plot
<<<<<<< HEAD:FlexDashBoard Matt Rachel Shayna Sherry.Rmd


answers <- clues %>% 
  select(category, answer, question)

#filter years out of answers, create new column, arrange descending
years_data <- answers %>% 
  mutate(years = str_extract(answer, "[0-9]{4}")) %>%
  filter(str_count(years)==4)%>% 
  arrange(desc(years)) %>% 
  slice(413:84470) %>% 
  group_by(years) 

 years_data1 <- years_data %>% 
   mutate(count = n()) %>% 
   arrange(desc(count)) %>% 
   ungroup()
 
 answers <- clues %>% 
  select(category, answer, question)

# transform years column to numeric
years2 <- transform(years_data1, years = as.numeric(years))

years2

# check data class
sapply(years2, mode)

 
library(ggthemes)
reference_plot <- 
  ggplot(years2, aes(x = years, y = count)) +
  geom_point()+
  coord_cartesian(xlim = c(1800,2019))+
  geom_vline(xintercept=1996,colour="blue")+
  geom_text(aes(x=1996,label="1996",y=1087,vjust=0,hjust=0),
            colour="black",
            text=element_text(size=11))+
  geom_text(x=1995,label=
              "US Olympics",y=200,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1861,colour="blue")+
  geom_text(x=1860, label=
              "American Civil War",y=350,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1914,colour="blue")+
  geom_text(x=1913,label="WWI",y=500,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1939,colour="blue")+
  geom_text(x=1938,label="WWII",y=500,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1955,colour="blue")+
  geom_text(x=1954,label="Vietnam",y=100,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=2005,colour="blue")+
  geom_text(x=2004,label="911 Attacks",y=200,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1963,colour="blue")+
  geom_text(x=1962,label=
              "JFK Assassination",y=100,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1986,colour="blue")+
  geom_text(x=1985,label=
              "Challenger Disaster",y=175,angle=90,vjust=0,hjust=0)+
  xlab("Years")+
  ylab("Number of times year given in clue")+
  ggtitle("Four digit years found in Jeopardy clues,Season 1-35",
          subtitle = "Truncated from 1800-2019")+
  theme_few()

reference_plot
=======
>>>>>>> d781491cef7db9ff9712c8b05cfc5bec08291a42:FlexDashBoard.Rmd
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
#trim out few rows with clues/questions in datatable
#try out story board layout
#dygraphs
#plotly
library(ggthemes)
line_plot <- ggplot(years2, aes(x = years, y = count)) +
  geom_line() +
  xlab("Years") +
  ylab("Number of times year given in clue")+
  ggtitle("Four digit years found in Jeopardy clues, Season 1-35") +
  theme_few()

line_plot
```

### Chart C

```{r}
sum_stats <- years2 %>% 
summarize(mean_count = mean(count))
sum_stats
mean_prop <- 
  sum_stats/84058
mean_prop  

prop_96 <-
  1087/84058 
prop_96

library(broom)
binom.test(x = 1087, n = 84058, p = 0.006) %>% 
  tidy()
```


