---
title: "R Final Project Markdown"
author: "Matthew Hughes, Sherry WeMott, Shayna Warner, Rachel Kanaziz"
date: "November 13, 2019"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(flexdashboard)
```

```{r}
# read in data
clues <- read_tsv("./data/master_season1-35.tsv")
```


```{r}

# Brooke also mentioned it would be interesing to look at lag time between air  
# date and the years that showed up in the questions (if that's something we 
# have time for)

answers <- clues %>% 
  select(category, answer, question)

#filter years out of answers, create new column, arrange descending
years_data <- answers %>% 
  mutate(years = str_extract(answer, "[0-9]{4}")) %>%
  filter(str_count(years)==4)%>% 
  arrange(desc(years)) %>% 
  slice(413:84470) %>% 
  group_by(years) 

 years_data1 <- years_data %>% 
   mutate(count = n()) %>% 
   arrange(desc(count)) %>% 
   ungroup()


```


```{r}
# transform years column to numeric
years2 <- transform(years_data1, years = as.numeric(years))

years2

# check data class
sapply(years2, mode)

```


```{r}
# try out a variety of sample plots 

ggplot(data = years2)+
 stat_count(mapping = aes(x = years), color = "dark green")

ggplot(years2, aes(x = years)) +
  stat_count(mapping = aes(x = years))

ggplot(years2, aes(x = years, y = count)) +
  geom_point()

ggplot(years2, aes(x = years, y = count)) +
  geom_col()

ggplot(years2, aes(x = years)) +
  geom_histogram()

<<<<<<< HEAD
library(ggthemes)
ggplot(years2, aes(x = years, y = count)) +
  geom_point()+
  coord_cartesian(xlim = c(1800,2019))+
  geom_vline(xintercept=1996,colour="blue")+
  geom_text(aes(x=1996,label="1996",y=1087,vjust=0,hjust=0),colour="black",text=element_text(size=11))+
  geom_text(x=1995,label="US Olympics",y=200,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1861,colour="blue")+
  geom_text(x=1860,label="American Civil War",y=350,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1914,colour="blue")+
  geom_text(x=1913,label="WWI",y=500,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1939,colour="blue")+
  geom_text(x=1938,label="WWII",y=500,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1955,colour="blue")+
  geom_text(x=1954,label="Vietnam",y=100,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=2005,colour="blue")+
  geom_text(x=2004,label="911 Attacks",y=200,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1963,colour="blue")+geom_text(x=1962,label="JFK Assassination",y=100,angle=90,vjust=0,hjust=0)+
  geom_vline(xintercept=1986,colour="blue")+
  geom_text(x=1985,label="Challenger Disaster",y=175,angle=90,vjust=0,hjust=0)+
  xlab("Years")+
  ylab("Number of times year given in clue")+
  ggtitle("Four digit years found in Jeopardy clues,Season 1-35",
          subtitle = "Truncated from 1800-2019")+
  theme_few()

#library(plotly)
#plot_ly(years2, type = "scatter", x = ~ years, y = ~count)

=======
# include this on flex dashboard
line_plot <- ggplot(years2, aes(x = years, y = count)) +
  geom_line() +
  xlab("Years") +
  ylab("Number of times year given in clue")+
  ggtitle("Four digit years found in Jeopardy clues, Season 1-35") +
  theme_few()
line_plot
>>>>>>> e0331088012aa13ed285cece9a85971c38b09dbc

scatter_plot
```  

```{r}
# pull out top 10 ranking years
top_10 <- tibble(Years = 
                   c(1996, 1999, 1997, 1980, 2000, 
                     1960, 1995, 1990, 1998, 1970), 
                Counts = c(1087, 1024, 1023, 999, 
                           994, 975, 961, 906, 891, 868))

library(knitr)
kable(top_10, 
      align = c("r","r"),
      caption = "Top 10 most mentioned years")
```

```{r}
# use prop.test in flex dashboard
sum_stats <- years2 %>% 
summarize(mean_count = mean(count))
sum_stats
mean_prop <- 
  sum_stats/84058
mean_prop  

prop_96 <-
  1087/84058 
prop_96

library(broom)
binom.test(x = 1087, n = 84058, p = 0.006) %>% 
  tidy()
```


